name: Test workflow to add issues to a project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'enhancement' 
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation add_to_project($planningProjectId:ID!, $sdhProjectId:ID!, $contentid:ID!) {
              planningProject: addProjectV2ItemById(input:{projectId:$planningProjectId contentId:$contentid}) {
                clientMutationId
              }
              sdhProject: addProjectV2ItemById(input:{projectId:$sdhProjectId contentId:$contentid}) {
                clientMutationId
              }
            }
          planningProjectId: "PVT_kwHN0jbOABe9dA"
          sdhProjectId: "PVT_kwHN0jbOABuDBg"
          contentid: ${{ github.event.issue.node_id }}
          GITHUB_TOKEN: ${{ secrets.TMP_ACCESS }}
