name: Test workflow to add issues to a project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'enhancement' 
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation add_to_project($planning_project_id:ID!, $sdh_project_id:ID!, $content_id:ID!) {
              planningProject: addProjectV2ItemById(input:{projectId:$planning_project_id contentId:$content_id}) {
                clientMutationId
              }
              sdhProject: addProjectV2ItemById(input:{projectId:$sdh_project_id contentId:$content_id}) {
                clientMutationId
              }
            }
          planning_project_id: "PVT_kwHN0jbOABe9dA"
          sdh_project_id: "PVT_kwHN0jbOABuDBg"
          content_id: ${{ github.event.issue.node_id }}
          GITHUB_TOKEN: ${{ secrets.TMP_ACCESS }}
