name: Test workflow to remove issues from a project

on:
  issues:
    types:
      - unlabeled

jobs:
  remove-from-project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'enhancement' 
    steps:
      - name: Get issue id from project
        id: get_issue_id_from_project
        env:
          GITHUB_TOKEN: ${{ secrets.TMP_ACCESS }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: "PVT_kwHN0jbOABe9dA"
        run: |
          gh api graphql -f query='
            mutation remove_from_project($projectid:ID!,$itemid:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $itemid}) {
                item {
                  id
                }
              }

              deleteProjectV2Item(input: {projectId: $project itemId: $addProjectV2ItemById.item.id}) {
                deletedItemId
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID
