name: Test workflow to remove issues from a project

on:
  issues:
    types:
      - unlabeled

jobs:
  remove-from-project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'enhancement' 
    steps:
      - name: Get issue id from project
        id: get_issue_id_from_project
        env:
          GITHUB_TOKEN: ${{ secrets.TMP_ACCESS }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: "PVT_kwHN0jbOABe9dA"
        run: |
          # The global issue id is not the same as the project-specific issue id, but there's
          # no API for retrieving an individual project issue, so we hack around that
          # limitation by using the idempotent addProjectV2ItemById operation
          item_id="$(gh api graphql -f query='
            mutation($project:ID!,$issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID --jq '.data.addProjectV2ItemById.item.id')"
            
          gh api graphql -f query='
            mutation($project:ID!,$item:ID!) {
              deleteProjectV2Item(input: {projectId: $project itemId: $item}) {
                deletedItemId
              }
            }' -f project=$PROJECT_ID -f item=$item_id
            
            
